# Generated by Django 3.0.11 on 2020-11-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewcounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageviewsmodel",
            name="views",
            field=models.IntegerField(default=1),
        ),
    ]
